// AUTO-GENERATED by scripts/sync-shared.mjs — edit shared/src instead, then run `npm run sync`
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.VehicleType = exports.TripType = exports.TripStatus = exports.Role = exports.RequestStatus = exports.QueueStatus = exports.PriorityTier = exports.LocationType = exports.GuestStatus = exports.DriverStatus = exports.AssignmentStrategy = void 0;
const Role = exports.Role = {
  ADMIN: 'admin',
  DRIVER: 'driver',
  GUEST: 'guest'
};
const DriverStatus = exports.DriverStatus = {
  OFFLINE: 'offline',
  IDLE: 'idle',
  ASSIGNED: 'assigned',
  EN_ROUTE_PICKUP: 'en_route_pickup',
  AT_PICKUP: 'at_pickup',
  ON_TRIP: 'on_trip',
  ON_BREAK: 'on_break',
  SUSPENDED: 'suspended'
};
const GuestStatus = exports.GuestStatus = {
  REGISTERED: 'registered',
  AWAITING_PICKUP: 'awaiting_pickup',
  QUEUED: 'queued',
  ASSIGNED: 'assigned',
  IN_TRANSIT: 'in_transit',
  COMPLETED: 'completed',
  NO_SHOW: 'no_show'
};
const TripType = exports.TripType = {
  ARRIVAL_PICKUP: 'ARRIVAL_PICKUP',
  TO_VENUE: 'TO_VENUE',
  FROM_VENUE: 'FROM_VENUE',
  DEPARTURE_DROP: 'DEPARTURE_DROP',
  INTER_HOTEL: 'INTER_HOTEL',
  ON_DEMAND: 'ON_DEMAND'
};
const TripStatus = exports.TripStatus = {
  PENDING_DRIVER: 'pending_driver',
  ACCEPTED: 'accepted',
  EN_ROUTE_PICKUP: 'en_route_pickup',
  AT_PICKUP: 'at_pickup',
  BOARDED: 'boarded',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  REJECTED: 'rejected',
  UNASSIGNABLE: 'unassignable'
};
const RequestStatus = exports.RequestStatus = {
  PENDING_APPROVAL: 'pending_approval',
  APPROVED: 'approved',
  DECLINED: 'declined',
  MATCHED: 'matched',
  EXPIRED: 'expired'
};
const QueueStatus = exports.QueueStatus = {
  WAITING: 'waiting',
  MATCHING: 'matching',
  ASSIGNED: 'assigned',
  FAILED: 'failed'
};
const LocationType = exports.LocationType = {
  AIRPORT: 'airport',
  RAILWAY_STATION: 'railway_station',
  ACCOMMODATION: 'accommodation',
  VENUE: 'venue',
  CUSTOM: 'custom'
};
const AssignmentStrategy = exports.AssignmentStrategy = {
  BATCH_HUNGARIAN: 'batch_hungarian',
  GREEDY_REALTIME: 'greedy_realtime',
  DETOUR_INSERT: 'detour_insert',
  MANUAL_OVERRIDE: 'manual_override',
  STARVATION_SWEEP: 'starvation_sweep'
};
const PriorityTier = exports.PriorityTier = {
  VIP: 3,
  SPEAKER: 2,
  STANDARD: 1
};
const VehicleType = exports.VehicleType = {
  SEDAN: 'sedan',
  SUV: 'suv',
  TEMPO: 'tempo',
  BUS: 'bus'
};