// Copies shared/src/** into apps/*/src/shared/ so every app has a single,
// zero-module-resolution-risk copy of the shared enums/events.
//
// shared/src is plain ESM JS (`export const ...`), which admin/guest copy
// verbatim since Vite bundles ESM directly. The server runs as plain
// CommonJS (`"type": "commonjs"`, no build step), so its copy is additionally
// transformed import/export -> require/module.exports via Babel at sync time
// — the same single source, compiled two ways, that shared/src used to get
// for free from each app's own (now-removed) TypeScript build step.
import { readdirSync, statSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformSync } from '@babel/core';
import commonjsPlugin from '@babel/plugin-transform-modules-commonjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const srcDir = join(root, 'shared', 'src');

const HEADER = '// AUTO-GENERATED by scripts/sync-shared.mjs — edit shared/src instead, then run `npm run sync`\n';

function copyDir(src, dest, { toCommonJs }) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry);
    const destPath = join(dest, entry);
    if (statSync(srcPath).isDirectory()) {
      copyDir(srcPath, destPath, { toCommonJs });
    } else if (entry.endsWith('.js')) {
      const contents = readFileSync(srcPath, 'utf8');
      const body = toCommonJs
        ? transformSync(contents, { filename: srcPath, plugins: [commonjsPlugin], configFile: false, babelrc: false }).code
        : contents;
      writeFileSync(destPath, HEADER + body);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

const targets = [
  { dir: join(root, 'apps', 'server', 'src', 'shared'), toCommonJs: true },
  { dir: join(root, 'apps', 'guest', 'src', 'shared'), toCommonJs: false },
  { dir: join(root, 'apps', 'admin', 'src', 'shared'), toCommonJs: false }
];

for (const { dir, toCommonJs } of targets) {
  copyDir(srcDir, dir, { toCommonJs });
  console.log(`synced shared/src -> ${dir.replace(root, '.')}`);
}
