// Copies shared/src/** into apps/*/src/shared/ so every app has a single,
// zero-module-resolution-risk copy of the shared types/enums/events.
// See plan.md §3 "Why shared/ is copied, not a workspace package".
import { readdirSync, statSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const srcDir = join(root, 'shared', 'src');
const targets = [
  join(root, 'apps', 'server', 'src', 'shared'),
  join(root, 'apps', 'guest', 'src', 'shared'),
  join(root, 'apps', 'admin', 'src', 'shared')
];

const HEADER = '// AUTO-GENERATED by scripts/sync-shared.mjs — edit shared/src instead, then run `npm run sync`\n';

function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry);
    const destPath = join(dest, entry);
    if (statSync(srcPath).isDirectory()) {
      copyDir(srcPath, destPath);
    } else if (entry.endsWith('.ts')) {
      const contents = readFileSync(srcPath, 'utf8');
      writeFileSync(destPath, HEADER + contents);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

for (const target of targets) {
  copyDir(srcDir, target);
  console.log(`synced shared/src -> ${target.replace(root, '.')}`);
}
