// AUTO-GENERATED by scripts/sync-shared.mjs — edit shared/src instead, then run `npm run sync`
// Socket.IO event names + payload types — single source of truth for client & server

export const ClientEvents = {
  DRIVER_LOCATION: 'driver:location',
  TRIP_SUBSCRIBE: 'trip:subscribe',
  ADMIN_SUBSCRIBE_MAP: 'admin:subscribeMap'
} as const;

export const ServerEvents = {
  TRIP_OFFERED: 'trip:offered',
  TRIP_ASSIGNED: 'trip:assigned',
  TRIP_STATUS: 'trip:status',
  TRIP_ETA: 'trip:eta',
  DRIVER_POSITION: 'driver:position',
  REQUEST_STATUS: 'request:status',
  QUEUE_UPDATE: 'queue:update',
  DISPATCH_TICK: 'dispatch:tick',
  ADMIN_ALERT: 'admin:alert',
  DRIVER_BREAK: 'driver:break'
} as const;

export interface DriverLocationPayload { lat: number; lng: number; heading?: number; speedKmph?: number }
export interface TripSubscribePayload { tripId: string }

export interface TripOfferedPayload { trip: unknown }
export interface TripAssignedPayload { trip: unknown; driver: { name: string; phone: string; vehicleNumber: string }; etaSeconds: number }
export interface TripStatusPayload { tripId: string; status: string; at: string; stopSeq?: number }
export interface TripEtaPayload { tripId: string; stops: Array<{ seq: number; etaAt: string }>; source: string }
export interface DriverPositionPayload { driverId: string; lat: number; lng: number; heading?: number; at: string }
export interface RequestStatusPayload { requestId: string; status: string; reason?: string }
export interface QueueUpdatePayload { depth: number; oldestWaitMin: number; unassignableCount: number }
export interface DispatchTickPayload { matched: number; unassignable: number; durationMs: number; at: string }
export interface AdminAlertPayload { id: string; level: 'info' | 'warning' | 'critical'; code: string; message: string; entity?: { type: string; id: string } }
export interface DriverBreakPayload { driverId: string; until: string; reason: string }
